# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Snake Sightings
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_custom.tasks.results import (
    combine_docx_files as combine_docx_files,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_geodataframes as view_state_from_geodataframes,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_taff.tasks import build_maps_context as build_maps_context
from ecoscope_workflows_ext_taff.tasks import (
    build_per_species_pages_docx as build_per_species_pages_docx,
)
from ecoscope_workflows_ext_taff.tasks import (
    build_species_summary_table as build_species_summary_table,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_observation_effort_grid as create_observation_effort_grid,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_report_template as create_report_template,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_species_richness_grid as create_species_richness_grid,
)
from ecoscope_workflows_ext_taff.tasks import (
    filter_binomial_species as filter_binomial_species,
)
from ecoscope_workflows_ext_taff.tasks import (
    generate_per_species_outputs as generate_per_species_outputs,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_png_paths as get_per_species_png_paths,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_species_names as get_per_species_species_names,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_widgets as get_per_species_widgets,
)
from ecoscope_workflows_ext_taff.tasks import parse_event_details as parse_event_details
from ecoscope_workflows_ext_taff.tasks import (
    prepare_all_species_points_gdf as prepare_all_species_points_gdf,
)
from ecoscope_workflows_ext_taff.tasks import (
    save_summary_table_as_docx as save_summary_table_as_docx,
)

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Define analysis time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Configure grouping strategy

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Connect to EarthRanger

# %%
# parameters

er_client_params = dict(
    data_source=...,
)

# %%
# call the task


er_client = (
    set_er_connection.set_task_instance_id("er_client")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_params)
    .call()
)


# %% [markdown]
# ## Fetch iNaturalist observations

# %%
# parameters

fetch_er_events_params = dict()

# %%
# call the task


fetch_er_events = (
    get_events.set_task_instance_id("fetch_er_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client,
        time_range=time_range,
        event_types=["inat_observation"],
        event_columns=[
            "id",
            "time",
            "event_type",
            "event_category",
            "title",
            "reported_by",
            "created_at",
            "serial_number",
            "is_collection",
            "event_details",
            "geometry",
        ],
        include_details=True,
        raise_on_empty=False,
        include_null_geometry=True,
        include_updates=False,
        include_related_events=False,
        include_display_values=True,
        **fetch_er_events_params,
    )
    .call()
)


# %% [markdown]
# ## Parse event details

# %%
# parameters

parse_details_params = dict()

# %%
# call the task


parse_details = (
    parse_event_details.set_task_instance_id("parse_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=fetch_er_events,
        fields=["taxon_name", "taxon_common_name", "user_name", "inat_id"],
        details_column="details",
        **parse_details_params,
    )
    .call()
)


# %% [markdown]
# ## Filter to valid binomial species

# %%
# parameters

filter_species_params = dict()

# %%
# call the task


filter_species = (
    filter_binomial_species.set_task_instance_id("filter_species")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=parse_details,
        name_column="taxon_name",
        remove_spatial_outliers=True,
        iqr_factor=3.0,
        **filter_species_params,
    )
    .call()
)


# %% [markdown]
# ## Build species summary table

# %%
# parameters

species_summary_df_params = dict()

# %%
# call the task


species_summary_df = (
    build_species_summary_table.set_task_instance_id("species_summary_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=filter_species,
        name_column="taxon_name",
        common_name_column="taxon_common_name",
        observer_column="user_name",
        id_column="inat_id",
        time_column="time",
        grid_size_meters=1000,
        planar_crs="EPSG:32737",
        **species_summary_df_params,
    )
    .call()
)


# %% [markdown]
# ## Save summary table as Word doc

# %%
# parameters

summary_table_docx_params = dict()

# %%
# call the task


summary_table_docx = (
    save_summary_table_as_docx.set_task_instance_id("summary_table_docx")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        table_df=species_summary_df,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename="species_summary_table.docx",
        font_name="Arial",
        font_size_pt=9,
        heading_font_size_pt=11,
        **summary_table_docx_params,
    )
    .call()
)


# %% [markdown]
# ## Render species summary table as HTML

# %%
# parameters

species_summary_html_params = dict(
    widget_id=...,
)

# %%
# call the task


species_summary_html = (
    draw_table.set_task_instance_id("species_summary_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=species_summary_df,
        columns=[
            "Number",
            "Scientific Name",
            "Common Name",
            "Observations",
            "Unique Observers",
            "Unique Locations",
            "First Observation",
            "Last Observation",
            "Range (km2)",
        ],
        table_config={
            "enable_sorting": True,
            "enable_filtering": False,
            "enable_download": False,
            "hide_header": False,
        },
        **species_summary_html_params,
    )
    .call()
)


# %% [markdown]
# ## Persist species summary table HTML

# %%
# parameters

persist_summary_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_summary_html = (
    persist_text.set_task_instance_id("persist_summary_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        text=species_summary_html,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="species_summary_table",
        **persist_summary_html_params,
    )
    .call()
)


# %% [markdown]
# ## Create summary table widget

# %%
# parameters

summary_table_widget_params = dict(
    view=...,
)

# %%
# call the task


summary_table_widget = (
    create_map_widget_single_view.set_task_instance_id("summary_table_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        title="Species Summary Table",
        data=persist_summary_html,
        **summary_table_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare all-species points GDF

# %%
# parameters

all_pts_gdf_params = dict()

# %%
# call the task


all_pts_gdf = (
    prepare_all_species_points_gdf.set_task_instance_id("all_pts_gdf")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(gdf=filter_species, **all_pts_gdf_params)
    .call()
)


# %% [markdown]
# ## All-species layer

# %%
# parameters

all_pts_layer_params = dict()

# %%
# call the task


all_pts_layer = (
    create_geojson_layer.set_task_instance_id("all_pts_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=all_pts_gdf,
        layer_style={
            "filled": True,
            "stroked": True,
            "get_fill_color": "fill_color",
            "get_line_color": "fill_color",
            "get_point_radius": 3,
            "point_radius_units": "pixels",
            "point_radius_min_pixels": 5,
            "opacity": 1.0,
        },
        legend={
            "title": "All Snake Species",
            "label_column": "bin_label",
            "color_column": "fill_color",
        },
        **all_pts_layer_params,
    )
    .call()
)


# %% [markdown]
# ## All-species view state

# %%
# parameters

all_view_state_params = dict()

# %%
# call the task


all_view_state = (
    view_state_from_geodataframes.set_task_instance_id("all_view_state")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(geodataframes=[all_pts_gdf], max_zoom=5, **all_view_state_params)
    .call()
)


# %% [markdown]
# ## Draw all-species map

# %%
# parameters

draw_all_species_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_all_species_map = (
    draw_map.set_task_instance_id("draw_all_species_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        geo_layers=[all_pts_layer],
        tile_layers=[
            {"layer_name": "TERRAIN", "opacity": 1.0},
            {"layer_name": "USGS HILLSHADE", "opacity": 0.25},
        ],
        view_state=all_view_state,
        static=True,
        title="All Snake Species Distribution",
        max_zoom=5,
        legend_style={"placement": "bottom-right"},
        **draw_all_species_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist all-species map HTML

# %%
# parameters

persist_all_species_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_all_species_html = (
    persist_text.set_task_instance_id("persist_all_species_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        text=draw_all_species_map,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="all_snakes_distribution",
        **persist_all_species_html_params,
    )
    .call()
)


# %% [markdown]
# ## All-species map widget

# %%
# parameters

all_species_widget_params = dict(
    view=...,
)

# %%
# call the task


all_species_widget = (
    create_map_widget_single_view.set_task_instance_id("all_species_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        title="All Snake Species Distribution",
        data=persist_all_species_html,
        **all_species_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Create observation effort grid

# %%
# parameters

effort_grid_params = dict()

# %%
# call the task


effort_grid = (
    create_observation_effort_grid.set_task_instance_id("effort_grid")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=filter_species,
        grid_size_meters=15000,
        planar_crs="EPSG:32737",
        output_crs="EPSG:4326",
        **effort_grid_params,
    )
    .call()
)


# %% [markdown]
# ## Effort map layer

# %%
# parameters

effort_layer_params = dict()

# %%
# call the task


effort_layer = (
    create_geojson_layer.set_task_instance_id("effort_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=effort_grid,
        layer_style={
            "filled": True,
            "stroked": True,
            "get_fill_color": "fill_color",
            "get_line_color": [80, 80, 80, 90],
            "get_line_width": 0.6,
            "opacity": 1.0,
        },
        legend={
            "title": "Observation Effort (15 km grid)",
            "label_column": "bin_label",
            "color_column": "fill_color",
            "sort": "ascending",
        },
        **effort_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Effort map view state

# %%
# parameters

effort_view_state_params = dict()

# %%
# call the task


effort_view_state = (
    view_state_from_geodataframes.set_task_instance_id("effort_view_state")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(geodataframes=[effort_grid], max_zoom=5, **effort_view_state_params)
    .call()
)


# %% [markdown]
# ## Draw observation effort map

# %%
# parameters

draw_effort_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_effort_map = (
    draw_map.set_task_instance_id("draw_effort_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        geo_layers=[effort_layer],
        tile_layers=[
            {"layer_name": "TERRAIN", "opacity": 1.0},
            {"layer_name": "USGS HILLSHADE", "opacity": 0.25},
        ],
        view_state=effort_view_state,
        static=True,
        title="Snake Observation Effort",
        max_zoom=5,
        legend_style={"placement": "bottom-right"},
        **draw_effort_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist effort map HTML

# %%
# parameters

persist_effort_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_effort_html = (
    persist_text.set_task_instance_id("persist_effort_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        text=draw_effort_map,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="observation_effort",
        **persist_effort_html_params,
    )
    .call()
)


# %% [markdown]
# ## Effort map widget

# %%
# parameters

effort_map_widget_params = dict(
    view=...,
)

# %%
# call the task


effort_map_widget = (
    create_map_widget_single_view.set_task_instance_id("effort_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        title="Snake Observation Effort",
        data=persist_effort_html,
        **effort_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Create species richness grid

# %%
# parameters

richness_grid_params = dict()

# %%
# call the task


richness_grid = (
    create_species_richness_grid.set_task_instance_id("richness_grid")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=filter_species,
        name_column="taxon_name",
        grid_size_meters=15000,
        planar_crs="EPSG:32737",
        output_crs="EPSG:4326",
        **richness_grid_params,
    )
    .call()
)


# %% [markdown]
# ## Richness map layer

# %%
# parameters

richness_layer_params = dict()

# %%
# call the task


richness_layer = (
    create_geojson_layer.set_task_instance_id("richness_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=richness_grid,
        layer_style={
            "filled": True,
            "stroked": True,
            "get_fill_color": "fill_color",
            "get_line_color": [80, 80, 80, 90],
            "get_line_width": 0.5,
            "opacity": 1.0,
        },
        legend={
            "title": "Snake Species Richness (15 km grid)",
            "label_column": "bin_label",
            "color_column": "fill_color",
            "sort": "ascending",
        },
        **richness_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Richness map view state

# %%
# parameters

richness_view_state_params = dict()

# %%
# call the task


richness_view_state = (
    view_state_from_geodataframes.set_task_instance_id("richness_view_state")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(geodataframes=[richness_grid], max_zoom=5, **richness_view_state_params)
    .call()
)


# %% [markdown]
# ## Draw species richness map

# %%
# parameters

draw_richness_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_richness_map = (
    draw_map.set_task_instance_id("draw_richness_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        geo_layers=[richness_layer],
        tile_layers=[
            {"layer_name": "TERRAIN", "opacity": 1.0},
            {"layer_name": "USGS HILLSHADE", "opacity": 0.25},
        ],
        view_state=richness_view_state,
        static=True,
        title="Snake Species Richness",
        max_zoom=5,
        legend_style={"placement": "bottom-right"},
        **draw_richness_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist richness map HTML

# %%
# parameters

persist_richness_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_richness_html = (
    persist_text.set_task_instance_id("persist_richness_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        text=draw_richness_map,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="species_richness",
        **persist_richness_html_params,
    )
    .call()
)


# %% [markdown]
# ## Richness map widget

# %%
# parameters

richness_map_widget_params = dict(
    view=...,
)

# %%
# call the task


richness_map_widget = (
    create_map_widget_single_view.set_task_instance_id("richness_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        title="Species Richness Map",
        data=persist_richness_html,
        **richness_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Generate all per-species outputs

# %%
# parameters

per_species_outputs_params = dict(
    top_n_by_count=...,
    species_summary_df=...,
)

# %%
# call the task


per_species_outputs = (
    generate_per_species_outputs.set_task_instance_id("per_species_outputs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        gdf=filter_species,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        name_column="taxon_name",
        buffer_fraction=0.15,
        zoom_extra=0,
        fallback_zoom=0,
        fallback_lat=0.0,
        fallback_lon=0.0,
        map_max_zoom=5,
        png_device_scale_factor=2.0,
        png_wait_for_timeout=15000,
        overlay_widget_scale=0.65,
        **per_species_outputs_params,
    )
    .call()
)


# %% [markdown]
# ## Extract per-species widgets

# %%
# parameters

per_species_widgets_params = dict()

# %%
# call the task


per_species_widgets = (
    get_per_species_widgets.set_task_instance_id("per_species_widgets")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(outputs=per_species_outputs, **per_species_widgets_params)
    .call()
)


# %% [markdown]
# ## Extract per-species PNG paths

# %%
# parameters

per_species_png_paths_params = dict()

# %%
# call the task


per_species_png_paths = (
    get_per_species_png_paths.set_task_instance_id("per_species_png_paths")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(outputs=per_species_outputs, **per_species_png_paths_params)
    .call()
)


# %% [markdown]
# ## Extract per-species species names

# %%
# parameters

per_species_species_names_params = dict()

# %%
# call the task


per_species_species_names = (
    get_per_species_species_names.set_task_instance_id("per_species_species_names")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(outputs=per_species_outputs, **per_species_species_names_params)
    .call()
)


# %% [markdown]
# ## Build per-species distribution pages Word doc

# %%
# parameters

per_species_pages_docx_params = dict()

# %%
# call the task


per_species_pages_docx = (
    build_per_species_pages_docx.set_task_instance_id("per_species_pages_docx")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        species_png_paths=per_species_png_paths,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        species_names=per_species_species_names,
        filename="per_species_maps.docx",
        use_landscape=False,
        maps_per_row=2,
        maps_per_col=3,
        heading_font_size_pt=7,
        font_name="Arial",
        **per_species_pages_docx_params,
    )
    .call()
)


# %% [markdown]
# ## Generate Word report template

# %%
# parameters

report_template_params = dict()

# %%
# call the task


report_template = (
    create_report_template.set_task_instance_id("report_template")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        taaf_logo_url="https://drive.google.com/uc?export=download&id=1oZN1HvRGiTVr62Bx-pUeGqAAMLT6vPFr",
        ecoscope_logo_url="https://drive.google.com/uc?export=download&id=1JrJaen6CppzKp9w6eXlmtkAJiwSGO06M",
        filename="report_template.docx",
        logo_download_timeout=45,
        **report_template_params,
    )
    .call()
)


# %% [markdown]
# ## Build report template context

# %%
# parameters

report_context_params = dict()

# %%
# call the task


report_context = (
    build_maps_context.set_task_instance_id("report_context")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        all_snakes_map_html=persist_all_species_html,
        effort_map_html=persist_effort_html,
        richness_map_html=persist_richness_html,
        generation_date=None,
        map_width_inches=6.0,
        device_scale_factor=2.0,
        wait_for_timeout=30000,
        **report_context_params,
    )
    .call()
)


# %% [markdown]
# ## Render main report sections

# %%
# parameters

render_report_body_params = dict()

# %%
# call the task


render_report_body = (
    create_docx.set_task_instance_id("render_report_body")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        template_path=report_template,
        context=report_context,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="snake_distribution_report",
        groupers=None,
        **render_report_body_params,
    )
    .call()
)


# %% [markdown]
# ## Assemble final report

# %%
# parameters

final_report_params = dict()

# %%
# call the task


final_report = (
    combine_docx_files.set_task_instance_id("final_report")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        master_file=render_report_body,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        output_filename="taaf_snake_distribution_report",
        file_paths=[summary_table_docx, per_species_pages_docx],
        restart_numbering=False,
        **final_report_params,
    )
    .call()
)


# %% [markdown]
# ## Snake sightings dashboard

# %%
# parameters

snake_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


snake_dashboard = (
    gather_dashboard.set_task_instance_id("snake_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[
            summary_table_widget,
            all_species_widget,
            effort_map_widget,
            richness_map_widget,
            per_species_widgets,
        ],
        time_range=time_range,
        groupers=groupers,
        **snake_dashboard_params,
    )
    .call()
)
