# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_custom.tasks.results import (
    combine_docx_files as combine_docx_files,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_geodataframes as view_state_from_geodataframes,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_taff.tasks import build_maps_context as build_maps_context
from ecoscope_workflows_ext_taff.tasks import (
    build_per_species_pages_docx as build_per_species_pages_docx,
)
from ecoscope_workflows_ext_taff.tasks import (
    build_species_summary_table as build_species_summary_table,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_observation_effort_grid as create_observation_effort_grid,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_report_template as create_report_template,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_species_richness_grid as create_species_richness_grid,
)
from ecoscope_workflows_ext_taff.tasks import (
    filter_binomial_species as filter_binomial_species,
)
from ecoscope_workflows_ext_taff.tasks import (
    generate_per_species_outputs as generate_per_species_outputs,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_png_paths as get_per_species_png_paths,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_species_names as get_per_species_species_names,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_widgets as get_per_species_widgets,
)
from ecoscope_workflows_ext_taff.tasks import parse_event_details as parse_event_details
from ecoscope_workflows_ext_taff.tasks import (
    prepare_all_species_points_gdf as prepare_all_species_points_gdf,
)
from ecoscope_workflows_ext_taff.tasks import (
    save_summary_table_as_docx as save_summary_table_as_docx,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client": [],
        "fetch_er_events": ["er_client", "time_range"],
        "parse_details": ["fetch_er_events"],
        "filter_species": ["parse_details"],
        "species_summary_df": ["filter_species"],
        "summary_table_docx": ["species_summary_df"],
        "species_summary_html": ["species_summary_df"],
        "persist_summary_html": ["species_summary_html"],
        "summary_table_widget": ["persist_summary_html"],
        "all_pts_gdf": ["filter_species"],
        "all_pts_layer": ["all_pts_gdf"],
        "all_view_state": ["all_pts_gdf"],
        "draw_all_species_map": ["all_pts_layer", "all_view_state"],
        "persist_all_species_html": ["draw_all_species_map"],
        "all_species_widget": ["persist_all_species_html"],
        "effort_grid": ["filter_species"],
        "effort_layer": ["effort_grid"],
        "effort_view_state": ["effort_grid"],
        "draw_effort_map": ["effort_layer", "effort_view_state"],
        "persist_effort_html": ["draw_effort_map"],
        "effort_map_widget": ["persist_effort_html"],
        "richness_grid": ["filter_species"],
        "richness_layer": ["richness_grid"],
        "richness_view_state": ["richness_grid"],
        "draw_richness_map": ["richness_layer", "richness_view_state"],
        "persist_richness_html": ["draw_richness_map"],
        "richness_map_widget": ["persist_richness_html"],
        "per_species_outputs": ["filter_species"],
        "per_species_widgets": ["per_species_outputs"],
        "per_species_png_paths": ["per_species_outputs"],
        "per_species_species_names": ["per_species_outputs"],
        "per_species_pages_docx": [
            "per_species_png_paths",
            "per_species_species_names",
        ],
        "report_template": [],
        "report_context": [
            "persist_all_species_html",
            "persist_effort_html",
            "persist_richness_html",
        ],
        "render_report_body": ["report_template", "report_context"],
        "final_report": [
            "render_report_body",
            "summary_table_docx",
            "per_species_pages_docx",
        ],
        "snake_dashboard": [
            "workflow_details",
            "summary_table_widget",
            "all_species_widget",
            "effort_map_widget",
            "richness_map_widget",
            "per_species_widgets",
            "time_range",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={} | (params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client") or {}),
            method="call",
        ),
        "fetch_er_events": Node(
            async_task=get_events.validate()
            .set_task_instance_id("fetch_er_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
                "time_range": DependsOn("time_range"),
                "event_types": [
                    "inat_observation",
                ],
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "event_category",
                    "title",
                    "reported_by",
                    "created_at",
                    "serial_number",
                    "is_collection",
                    "event_details",
                    "geometry",
                ],
                "include_details": True,
                "raise_on_empty": False,
                "include_null_geometry": True,
                "include_updates": False,
                "include_related_events": False,
                "include_display_values": True,
            }
            | (params_dict.get("fetch_er_events") or {}),
            method="call",
        ),
        "parse_details": Node(
            async_task=parse_event_details.validate()
            .set_task_instance_id("parse_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("fetch_er_events"),
                "fields": [
                    "taxon_name",
                    "taxon_common_name",
                    "user_name",
                    "inat_id",
                ],
                "details_column": "details",
            }
            | (params_dict.get("parse_details") or {}),
            method="call",
        ),
        "filter_species": Node(
            async_task=filter_binomial_species.validate()
            .set_task_instance_id("filter_species")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("parse_details"),
                "name_column": "taxon_name",
                "remove_spatial_outliers": True,
                "iqr_factor": 3.0,
            }
            | (params_dict.get("filter_species") or {}),
            method="call",
        ),
        "species_summary_df": Node(
            async_task=build_species_summary_table.validate()
            .set_task_instance_id("species_summary_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("filter_species"),
                "name_column": "taxon_name",
                "common_name_column": "taxon_common_name",
                "observer_column": "user_name",
                "id_column": "inat_id",
                "time_column": "time",
                "grid_size_meters": 1000,
                "planar_crs": "EPSG:32737",
            }
            | (params_dict.get("species_summary_df") or {}),
            method="call",
        ),
        "summary_table_docx": Node(
            async_task=save_summary_table_as_docx.validate()
            .set_task_instance_id("summary_table_docx")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "table_df": DependsOn("species_summary_df"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename": "species_summary_table.docx",
                "font_name": "Arial",
                "font_size_pt": 9,
                "heading_font_size_pt": 11,
            }
            | (params_dict.get("summary_table_docx") or {}),
            method="call",
        ),
        "species_summary_html": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("species_summary_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("species_summary_df"),
                "columns": [
                    "Number",
                    "Scientific Name",
                    "Common Name",
                    "Observations",
                    "Unique Observers",
                    "Unique Locations",
                    "First Observation",
                    "Last Observation",
                    "Range (km2)",
                ],
                "table_config": {
                    "enable_sorting": True,
                    "enable_filtering": False,
                    "enable_download": False,
                    "hide_header": False,
                },
            }
            | (params_dict.get("species_summary_html") or {}),
            method="call",
        ),
        "persist_summary_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_summary_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("species_summary_html"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "species_summary_table",
            }
            | (params_dict.get("persist_summary_html") or {}),
            method="call",
        ),
        "summary_table_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("summary_table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Species Summary Table",
                "data": DependsOn("persist_summary_html"),
            }
            | (params_dict.get("summary_table_widget") or {}),
            method="call",
        ),
        "all_pts_gdf": Node(
            async_task=prepare_all_species_points_gdf.validate()
            .set_task_instance_id("all_pts_gdf")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("filter_species"),
            }
            | (params_dict.get("all_pts_gdf") or {}),
            method="call",
        ),
        "all_pts_layer": Node(
            async_task=create_geojson_layer.validate()
            .set_task_instance_id("all_pts_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "geodataframe": DependsOn("all_pts_gdf"),
                "layer_style": {
                    "filled": True,
                    "stroked": True,
                    "get_fill_color": "fill_color",
                    "get_line_color": "fill_color",
                    "get_point_radius": 3,
                    "point_radius_units": "pixels",
                    "point_radius_min_pixels": 5,
                    "opacity": 1.0,
                },
                "legend": {
                    "title": "All Snake Species",
                    "label_column": "bin_label",
                    "color_column": "fill_color",
                },
            }
            | (params_dict.get("all_pts_layer") or {}),
            method="call",
        ),
        "all_view_state": Node(
            async_task=view_state_from_geodataframes.validate()
            .set_task_instance_id("all_view_state")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframes": [
                    DependsOn("all_pts_gdf"),
                ],
                "max_zoom": 5,
            }
            | (params_dict.get("all_view_state") or {}),
            method="call",
        ),
        "draw_all_species_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_all_species_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": [
                    DependsOn("all_pts_layer"),
                ],
                "tile_layers": [
                    {
                        "layer_name": "TERRAIN",
                        "opacity": 1.0,
                    },
                    {
                        "layer_name": "USGS HILLSHADE",
                        "opacity": 0.25,
                    },
                ],
                "view_state": DependsOn("all_view_state"),
                "static": True,
                "title": "All Snake Species Distribution",
                "max_zoom": 5,
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("draw_all_species_map") or {}),
            method="call",
        ),
        "persist_all_species_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_all_species_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("draw_all_species_map"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "all_snakes_distribution",
            }
            | (params_dict.get("persist_all_species_html") or {}),
            method="call",
        ),
        "all_species_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("all_species_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "All Snake Species Distribution",
                "data": DependsOn("persist_all_species_html"),
            }
            | (params_dict.get("all_species_widget") or {}),
            method="call",
        ),
        "effort_grid": Node(
            async_task=create_observation_effort_grid.validate()
            .set_task_instance_id("effort_grid")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("filter_species"),
                "grid_size_meters": 15000,
                "planar_crs": "EPSG:32737",
                "output_crs": "EPSG:4326",
            }
            | (params_dict.get("effort_grid") or {}),
            method="call",
        ),
        "effort_layer": Node(
            async_task=create_geojson_layer.validate()
            .set_task_instance_id("effort_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "geodataframe": DependsOn("effort_grid"),
                "layer_style": {
                    "filled": True,
                    "stroked": True,
                    "get_fill_color": "fill_color",
                    "get_line_color": [
                        80,
                        80,
                        80,
                        90,
                    ],
                    "get_line_width": 0.6,
                    "opacity": 1.0,
                },
                "legend": {
                    "title": "Observation Effort (15 km grid)",
                    "label_column": "bin_label",
                    "color_column": "fill_color",
                    "sort": "ascending",
                },
            }
            | (params_dict.get("effort_layer") or {}),
            method="call",
        ),
        "effort_view_state": Node(
            async_task=view_state_from_geodataframes.validate()
            .set_task_instance_id("effort_view_state")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframes": [
                    DependsOn("effort_grid"),
                ],
                "max_zoom": 5,
            }
            | (params_dict.get("effort_view_state") or {}),
            method="call",
        ),
        "draw_effort_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_effort_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": [
                    DependsOn("effort_layer"),
                ],
                "tile_layers": [
                    {
                        "layer_name": "TERRAIN",
                        "opacity": 1.0,
                    },
                    {
                        "layer_name": "USGS HILLSHADE",
                        "opacity": 0.25,
                    },
                ],
                "view_state": DependsOn("effort_view_state"),
                "static": True,
                "title": "Snake Observation Effort",
                "max_zoom": 5,
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("draw_effort_map") or {}),
            method="call",
        ),
        "persist_effort_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_effort_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("draw_effort_map"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "observation_effort",
            }
            | (params_dict.get("persist_effort_html") or {}),
            method="call",
        ),
        "effort_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("effort_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Snake Observation Effort",
                "data": DependsOn("persist_effort_html"),
            }
            | (params_dict.get("effort_map_widget") or {}),
            method="call",
        ),
        "richness_grid": Node(
            async_task=create_species_richness_grid.validate()
            .set_task_instance_id("richness_grid")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("filter_species"),
                "name_column": "taxon_name",
                "grid_size_meters": 15000,
                "planar_crs": "EPSG:32737",
                "output_crs": "EPSG:4326",
            }
            | (params_dict.get("richness_grid") or {}),
            method="call",
        ),
        "richness_layer": Node(
            async_task=create_geojson_layer.validate()
            .set_task_instance_id("richness_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "geodataframe": DependsOn("richness_grid"),
                "layer_style": {
                    "filled": True,
                    "stroked": True,
                    "get_fill_color": "fill_color",
                    "get_line_color": [
                        80,
                        80,
                        80,
                        90,
                    ],
                    "get_line_width": 0.5,
                    "opacity": 1.0,
                },
                "legend": {
                    "title": "Snake Species Richness (15 km grid)",
                    "label_column": "bin_label",
                    "color_column": "fill_color",
                    "sort": "ascending",
                },
            }
            | (params_dict.get("richness_layer") or {}),
            method="call",
        ),
        "richness_view_state": Node(
            async_task=view_state_from_geodataframes.validate()
            .set_task_instance_id("richness_view_state")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframes": [
                    DependsOn("richness_grid"),
                ],
                "max_zoom": 5,
            }
            | (params_dict.get("richness_view_state") or {}),
            method="call",
        ),
        "draw_richness_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_richness_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": [
                    DependsOn("richness_layer"),
                ],
                "tile_layers": [
                    {
                        "layer_name": "TERRAIN",
                        "opacity": 1.0,
                    },
                    {
                        "layer_name": "USGS HILLSHADE",
                        "opacity": 0.25,
                    },
                ],
                "view_state": DependsOn("richness_view_state"),
                "static": True,
                "title": "Snake Species Richness",
                "max_zoom": 5,
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("draw_richness_map") or {}),
            method="call",
        ),
        "persist_richness_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_richness_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("draw_richness_map"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "species_richness",
            }
            | (params_dict.get("persist_richness_html") or {}),
            method="call",
        ),
        "richness_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("richness_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Species Richness Map",
                "data": DependsOn("persist_richness_html"),
            }
            | (params_dict.get("richness_map_widget") or {}),
            method="call",
        ),
        "per_species_outputs": Node(
            async_task=generate_per_species_outputs.validate()
            .set_task_instance_id("per_species_outputs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("filter_species"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "name_column": "taxon_name",
                "buffer_fraction": 0.15,
                "zoom_extra": 0,
                "fallback_zoom": 0,
                "fallback_lat": 0.0,
                "fallback_lon": 0.0,
                "map_max_zoom": 5,
                "png_device_scale_factor": 2.0,
                "png_wait_for_timeout": 15000,
                "overlay_widget_scale": 0.65,
            }
            | (params_dict.get("per_species_outputs") or {}),
            method="call",
        ),
        "per_species_widgets": Node(
            async_task=get_per_species_widgets.validate()
            .set_task_instance_id("per_species_widgets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "outputs": DependsOn("per_species_outputs"),
            }
            | (params_dict.get("per_species_widgets") or {}),
            method="call",
        ),
        "per_species_png_paths": Node(
            async_task=get_per_species_png_paths.validate()
            .set_task_instance_id("per_species_png_paths")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "outputs": DependsOn("per_species_outputs"),
            }
            | (params_dict.get("per_species_png_paths") or {}),
            method="call",
        ),
        "per_species_species_names": Node(
            async_task=get_per_species_species_names.validate()
            .set_task_instance_id("per_species_species_names")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "outputs": DependsOn("per_species_outputs"),
            }
            | (params_dict.get("per_species_species_names") or {}),
            method="call",
        ),
        "per_species_pages_docx": Node(
            async_task=build_per_species_pages_docx.validate()
            .set_task_instance_id("per_species_pages_docx")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "species_png_paths": DependsOn("per_species_png_paths"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "species_names": DependsOn("per_species_species_names"),
                "filename": "per_species_maps.docx",
                "use_landscape": False,
                "maps_per_row": 2,
                "maps_per_col": 3,
                "heading_font_size_pt": 7,
                "font_name": "Arial",
            }
            | (params_dict.get("per_species_pages_docx") or {}),
            method="call",
        ),
        "report_template": Node(
            async_task=create_report_template.validate()
            .set_task_instance_id("report_template")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "taaf_logo_url": "https://drive.google.com/uc?export=download&id=1oZN1HvRGiTVr62Bx-pUeGqAAMLT6vPFr",
                "ecoscope_logo_url": "https://drive.google.com/uc?export=download&id=1JrJaen6CppzKp9w6eXlmtkAJiwSGO06M",
                "filename": "report_template.docx",
                "logo_download_timeout": 45,
            }
            | (params_dict.get("report_template") or {}),
            method="call",
        ),
        "report_context": Node(
            async_task=build_maps_context.validate()
            .set_task_instance_id("report_context")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "all_snakes_map_html": DependsOn("persist_all_species_html"),
                "effort_map_html": DependsOn("persist_effort_html"),
                "richness_map_html": DependsOn("persist_richness_html"),
                "generation_date": None,
                "map_width_inches": 6.0,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 30000,
            }
            | (params_dict.get("report_context") or {}),
            method="call",
        ),
        "render_report_body": Node(
            async_task=create_docx.validate()
            .set_task_instance_id("render_report_body")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "template_path": DependsOn("report_template"),
                "context": DependsOn("report_context"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "snake_distribution_report",
                "groupers": None,
            }
            | (params_dict.get("render_report_body") or {}),
            method="call",
        ),
        "final_report": Node(
            async_task=combine_docx_files.validate()
            .set_task_instance_id("final_report")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "master_file": DependsOn("render_report_body"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "output_filename": "taaf_snake_distribution_report",
                "file_paths": [
                    DependsOn("summary_table_docx"),
                    DependsOn("per_species_pages_docx"),
                ],
                "restart_numbering": False,
            }
            | (params_dict.get("final_report") or {}),
            method="call",
        ),
        "snake_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("snake_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("summary_table_widget"),
                    DependsOn("all_species_widget"),
                    DependsOn("effort_map_widget"),
                    DependsOn("richness_map_widget"),
                    DependsOn("per_species_widgets"),
                ],
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("snake_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
