# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_custom.tasks.results import (
    combine_docx_files as combine_docx_files,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_geodataframes as view_state_from_geodataframes,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_taff.tasks import build_maps_context as build_maps_context
from ecoscope_workflows_ext_taff.tasks import (
    build_per_species_pages_docx as build_per_species_pages_docx,
)
from ecoscope_workflows_ext_taff.tasks import (
    build_species_summary_table as build_species_summary_table,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_observation_effort_grid as create_observation_effort_grid,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_report_template as create_report_template,
)
from ecoscope_workflows_ext_taff.tasks import (
    create_species_richness_grid as create_species_richness_grid,
)
from ecoscope_workflows_ext_taff.tasks import (
    filter_binomial_species as filter_binomial_species,
)
from ecoscope_workflows_ext_taff.tasks import (
    generate_per_species_outputs as generate_per_species_outputs,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_png_paths as get_per_species_png_paths,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_species_names as get_per_species_species_names,
)
from ecoscope_workflows_ext_taff.tasks import (
    get_per_species_widgets as get_per_species_widgets,
)
from ecoscope_workflows_ext_taff.tasks import parse_event_details as parse_event_details
from ecoscope_workflows_ext_taff.tasks import (
    prepare_all_species_points_gdf as prepare_all_species_points_gdf,
)
from ecoscope_workflows_ext_taff.tasks import (
    save_summary_table_as_docx as save_summary_table_as_docx,
)
from ecoscope_workflows_ext_taff.tasks import take_first_n_items as take_first_n_items

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    er_client = (
        set_er_connection.validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("er_client") or {}))
        .call()
    )

    fetch_er_events = (
        get_events.validate()
        .set_task_instance_id("fetch_er_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_types=["inat_observation"],
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "title",
                "reported_by",
                "created_at",
                "serial_number",
                "is_collection",
                "event_details",
                "geometry",
            ],
            include_details=True,
            raise_on_empty=False,
            include_null_geometry=True,
            include_updates=False,
            include_related_events=False,
            include_display_values=True,
            **(params_dict.get("fetch_er_events") or {}),
        )
        .call()
    )

    parse_details = (
        parse_event_details.validate()
        .set_task_instance_id("parse_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=fetch_er_events,
            fields=["taxon_name", "taxon_common_name", "user_name", "inat_id"],
            details_column="details",
            **(params_dict.get("parse_details") or {}),
        )
        .call()
    )

    filter_species = (
        filter_binomial_species.validate()
        .set_task_instance_id("filter_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=parse_details,
            name_column="taxon_name",
            remove_spatial_outliers=True,
            iqr_factor=3.0,
            **(params_dict.get("filter_species") or {}),
        )
        .call()
    )

    species_summary_df = (
        build_species_summary_table.validate()
        .set_task_instance_id("species_summary_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=filter_species,
            name_column="taxon_name",
            common_name_column="taxon_common_name",
            observer_column="user_name",
            id_column="inat_id",
            time_column="time",
            grid_size_meters=1000,
            planar_crs="EPSG:32737",
            **(params_dict.get("species_summary_df") or {}),
        )
        .call()
    )

    summary_table_docx = (
        save_summary_table_as_docx.validate()
        .set_task_instance_id("summary_table_docx")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            table_df=species_summary_df,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="species_summary_table.docx",
            font_name="Arial",
            font_size_pt=9,
            heading_font_size_pt=11,
            **(params_dict.get("summary_table_docx") or {}),
        )
        .call()
    )

    species_summary_html = (
        draw_table.validate()
        .set_task_instance_id("species_summary_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=species_summary_df,
            columns=[
                "Number",
                "Scientific Name",
                "Common Name",
                "Observations",
                "Unique Observers",
                "Unique Locations",
                "First Observation",
                "Last Observation",
                "Range (km2)",
            ],
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": False,
                "hide_header": False,
            },
            **(params_dict.get("species_summary_html") or {}),
        )
        .call()
    )

    persist_summary_html = (
        persist_text.validate()
        .set_task_instance_id("persist_summary_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            text=species_summary_html,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="species_summary_table",
            **(params_dict.get("persist_summary_html") or {}),
        )
        .call()
    )

    summary_table_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("summary_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            title="Species Summary Table",
            data=persist_summary_html,
            **(params_dict.get("summary_table_widget") or {}),
        )
        .call()
    )

    all_pts_gdf = (
        prepare_all_species_points_gdf.validate()
        .set_task_instance_id("all_pts_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(gdf=filter_species, **(params_dict.get("all_pts_gdf") or {}))
        .call()
    )

    all_pts_layer = (
        create_geojson_layer.validate()
        .set_task_instance_id("all_pts_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=all_pts_gdf,
            layer_style={
                "filled": True,
                "stroked": True,
                "get_fill_color": "fill_color",
                "get_line_color": "fill_color",
                "get_point_radius": 3,
                "point_radius_units": "pixels",
                "point_radius_min_pixels": 5,
                "opacity": 1.0,
            },
            legend={
                "title": "All Snake Species",
                "label_column": "bin_label",
                "color_column": "fill_color",
            },
            **(params_dict.get("all_pts_layer") or {}),
        )
        .call()
    )

    all_view_state = (
        view_state_from_geodataframes.validate()
        .set_task_instance_id("all_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            geodataframes=[all_pts_gdf],
            max_zoom=7,
            **(params_dict.get("all_view_state") or {}),
        )
        .call()
    )

    draw_all_species_map = (
        draw_map.validate()
        .set_task_instance_id("draw_all_species_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            geo_layers=[all_pts_layer],
            tile_layers=[
                {"layer_name": "TERRAIN", "opacity": 1.0},
                {"layer_name": "USGS HILLSHADE", "opacity": 0.25},
            ],
            view_state=all_view_state,
            static=True,
            title=None,
            max_zoom=7,
            legend_style={"placement": "bottom-right"},
            **(params_dict.get("draw_all_species_map") or {}),
        )
        .call()
    )

    persist_all_species_html = (
        persist_text.validate()
        .set_task_instance_id("persist_all_species_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            text=draw_all_species_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="all_snakes_distribution",
            **(params_dict.get("persist_all_species_html") or {}),
        )
        .call()
    )

    all_species_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("all_species_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            title="All Snake Species Distribution",
            data=persist_all_species_html,
            **(params_dict.get("all_species_widget") or {}),
        )
        .call()
    )

    per_species_outputs = (
        generate_per_species_outputs.validate()
        .set_task_instance_id("per_species_outputs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            gdf=filter_species,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            name_column="taxon_name",
            top_n_by_count=None,
            species_summary_df=species_summary_df,
            buffer_fraction=0.15,
            zoom_extra=0,
            fallback_zoom=0,
            fallback_lat=0.0,
            fallback_lon=0.0,
            map_max_zoom=7,
            png_device_scale_factor=2.0,
            png_wait_for_timeout=15000,
            overlay_widget_scale=0.65,
            **(params_dict.get("per_species_outputs") or {}),
        )
        .call()
    )

    per_species_widgets = (
        get_per_species_widgets.validate()
        .set_task_instance_id("per_species_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            outputs=per_species_outputs,
            **(params_dict.get("per_species_widgets") or {}),
        )
        .call()
    )

    per_species_png_paths = (
        get_per_species_png_paths.validate()
        .set_task_instance_id("per_species_png_paths")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            outputs=per_species_outputs,
            **(params_dict.get("per_species_png_paths") or {}),
        )
        .call()
    )

    per_species_species_names = (
        get_per_species_species_names.validate()
        .set_task_instance_id("per_species_species_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            outputs=per_species_outputs,
            **(params_dict.get("per_species_species_names") or {}),
        )
        .call()
    )

    top10_per_species_widgets = (
        take_first_n_items.validate()
        .set_task_instance_id("top10_per_species_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            items=per_species_widgets,
            n=10,
            **(params_dict.get("top10_per_species_widgets") or {}),
        )
        .call()
    )

    effort_grid = (
        create_observation_effort_grid.validate()
        .set_task_instance_id("effort_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=filter_species,
            grid_size_meters=15000,
            planar_crs="EPSG:32737",
            output_crs="EPSG:4326",
            **(params_dict.get("effort_grid") or {}),
        )
        .call()
    )

    effort_layer = (
        create_geojson_layer.validate()
        .set_task_instance_id("effort_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=effort_grid,
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "density_colors",
                "get_line_color": [0, 0, 0],
                "opacity": 0.75,
                "get_line_width": 0.85,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Observation Effort",
                "label_column": "density_bins",
                "color_column": "density_colors",
            },
            **(params_dict.get("effort_layer") or {}),
        )
        .call()
    )

    effort_view_state = (
        view_state_from_geodataframes.validate()
        .set_task_instance_id("effort_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            geodataframes=[effort_grid],
            max_zoom=7,
            **(params_dict.get("effort_view_state") or {}),
        )
        .call()
    )

    draw_effort_map = (
        draw_map.validate()
        .set_task_instance_id("draw_effort_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            geo_layers=[effort_layer],
            tile_layers=[
                {"layer_name": "TERRAIN", "opacity": 1.0},
                {"layer_name": "USGS HILLSHADE", "opacity": 0.25},
            ],
            view_state=effort_view_state,
            static=True,
            title=None,
            max_zoom=7,
            legend_style={"placement": "bottom-right"},
            **(params_dict.get("draw_effort_map") or {}),
        )
        .call()
    )

    persist_effort_html = (
        persist_text.validate()
        .set_task_instance_id("persist_effort_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            text=draw_effort_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="observation_effort",
            **(params_dict.get("persist_effort_html") or {}),
        )
        .call()
    )

    effort_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("effort_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            title="Snake Observation Effort",
            data=persist_effort_html,
            **(params_dict.get("effort_map_widget") or {}),
        )
        .call()
    )

    richness_grid = (
        create_species_richness_grid.validate()
        .set_task_instance_id("richness_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=filter_species,
            name_column="taxon_name",
            grid_size_meters=15000,
            planar_crs="EPSG:32737",
            output_crs="EPSG:4326",
            **(params_dict.get("richness_grid") or {}),
        )
        .call()
    )

    richness_layer = (
        create_geojson_layer.validate()
        .set_task_instance_id("richness_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=richness_grid,
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "density_colors",
                "get_line_color": [0, 0, 0],
                "opacity": 0.75,
                "get_line_width": 0.85,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Snake Species Richness",
                "label_column": "density_bins",
                "color_column": "density_colors",
            },
            **(params_dict.get("richness_layer") or {}),
        )
        .call()
    )

    richness_view_state = (
        view_state_from_geodataframes.validate()
        .set_task_instance_id("richness_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            geodataframes=[richness_grid],
            max_zoom=7,
            **(params_dict.get("richness_view_state") or {}),
        )
        .call()
    )

    draw_richness_map = (
        draw_map.validate()
        .set_task_instance_id("draw_richness_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            geo_layers=[richness_layer],
            tile_layers=[
                {"layer_name": "TERRAIN", "opacity": 1.0},
                {"layer_name": "USGS HILLSHADE", "opacity": 0.25},
            ],
            view_state=richness_view_state,
            static=True,
            title=None,
            max_zoom=7,
            legend_style={"placement": "bottom-right"},
            **(params_dict.get("draw_richness_map") or {}),
        )
        .call()
    )

    persist_richness_html = (
        persist_text.validate()
        .set_task_instance_id("persist_richness_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            text=draw_richness_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="species_richness",
            **(params_dict.get("persist_richness_html") or {}),
        )
        .call()
    )

    richness_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("richness_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            title="Species Richness Map",
            data=persist_richness_html,
            **(params_dict.get("richness_map_widget") or {}),
        )
        .call()
    )

    report_template = (
        create_report_template.validate()
        .set_task_instance_id("report_template")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            taaf_logo_url="https://drive.google.com/uc?export=download&id=1oZN1HvRGiTVr62Bx-pUeGqAAMLT6vPFr",
            ecoscope_logo_url="https://drive.google.com/uc?export=download&id=1JrJaen6CppzKp9w6eXlmtkAJiwSGO06M",
            filename="report_template.docx",
            logo_download_timeout=45,
            **(params_dict.get("report_template") or {}),
        )
        .call()
    )

    report_context = (
        build_maps_context.validate()
        .set_task_instance_id("report_context")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            all_snakes_map_html=persist_all_species_html,
            effort_map_html=persist_effort_html,
            richness_map_html=persist_richness_html,
            generation_date=None,
            map_width_inches=6.0,
            device_scale_factor=2.0,
            wait_for_timeout=30000,
            **(params_dict.get("report_context") or {}),
        )
        .call()
    )

    render_report_body = (
        create_docx.validate()
        .set_task_instance_id("render_report_body")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            template_path=report_template,
            context=report_context,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="snake_distribution_report",
            groupers=None,
            **(params_dict.get("render_report_body") or {}),
        )
        .call()
    )

    per_species_pages_docx = (
        build_per_species_pages_docx.validate()
        .set_task_instance_id("per_species_pages_docx")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            species_png_paths=per_species_png_paths,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            species_names=per_species_species_names,
            filename="per_species_maps.docx",
            use_landscape=False,
            maps_per_row=2,
            maps_per_col=3,
            heading_font_size_pt=7,
            font_name="Arial",
            **(params_dict.get("per_species_pages_docx") or {}),
        )
        .call()
    )

    final_report = (
        combine_docx_files.validate()
        .set_task_instance_id("final_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            master_file=render_report_body,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            output_filename="taaf_snake_distribution_report",
            file_paths=[summary_table_docx, per_species_pages_docx],
            restart_numbering=False,
            **(params_dict.get("final_report") or {}),
        )
        .call()
    )

    snake_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("snake_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                summary_table_widget,
                all_species_widget,
                richness_map_widget,
                effort_map_widget,
                top10_per_species_widgets,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("snake_dashboard") or {}),
        )
        .call()
    )

    return snake_dashboard
